name: Terraform Plan

on:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Terraform Plan Setup
        uses: mleager/tf-shared-actions/.github/actions/terraform-plan@main
        with:
          bucket: tf-state-8864
          key: tf-s3-global-state/terraform.tfstate
          region: ${{ vars.AWS_REGION }}
          var_file: terraform.tfvars.development
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

