name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY" to confirm resource destruction'
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      CONFIG_DIRECTORY: ./terraform
      STATE_BUCKET: tf-state-8864
      AWS_REGION: us-east-1
      ENVIRONMENT: development
    # environment: ${{ env.ENVIRONMENT }}
    permissions:
      contents: write
      id-token: write
    defaults:
      run:
        working-directory: ${{ env.CONFIG_DIRECTORY }}
    steps:
    - name: Terraform Destroy
      uses: mleager/tf-shared-actions/.github/actions/terraform-destroy@main
      with:
        create_oidc_role: false
        oidc_role: ${{ secrets.OIDC_ROLE }}
        aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        project_name: ${{ env.PROJECT_NAME }}
        environment: ${{ env.ENVIRONMENT }}
        bucket: ${{ env.STATE_BUCKET }}
        key: ${{ secrets.S3_KEY }}/terraform.tfstate
        region: ${{ env.AWS_REGION }}
        var_file: terraform.tfvars.${{ env.ENVIRONMENT }}
        make_commit_comment: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

